development:
  bucket: 'myfaithshines'
  access_key_id: 'AKIAIS3MSX5IYHIWE3BA'
  secret_access_key: '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'
#  server: 's3-us-west-2.amazonaws.com'
# test:
#  bucket: 'GoodDogTest'
#  access_key_id: 'AKIAIDF7RBTQFX676MCA'
#  secret_access_key: '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'

production:
  bucket: 'myfaithshines'
  access_key_id: 'AKIAIS3MSX5IYHIWE3BA'
  secret_access_key: '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'
#  server: 's3-us-west-2.amazonaws.com'
